steps:
  # Push the container image to Container Registry
  - name: "gcr.io/jolly-mountain/jolly_app"
    args: ["push", "gcr.io/jolly-mountain/jolly_app"]
    id: Pushing the image to registry
  # Deploy container image to Cloud Run
  - name: "gcr.io/jolly-mountain/jolly_app"
    args:
      [
        "run",
        "deploy",
        "jolly_app",
        "--image",
        "gcr.io/jolly-mountain/jolly_app",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
